platform: linux

image_resource:
  type: docker-image
  source: {repository: node, tag: "6" }
inputs:
- name: cnets-chat-git
  path: ./frontend
- name: dependency-cache
run:
  path: cnets-chat-git/ci/script/build-frontend.sh