platform: linux

image_resource:
  type: docker-image
  source: {repository: node, tag: "6" }

inputs:
- name: cnets-chat-git
  path: /

- name: dependency-cache
  path: /cache

outputs:
- name: frontend-public
  
run:
  path: sh
  args:
    - -exc
    - |
      export API_URL=https://cnets-chat-demo-backend.uk-1.cf-app.net
      mv cache/node_modules frontend
      cd frontend && npm run build && ls -LR public
      cp -a public/. ../frontend-public && ls -LR ..