platform: linux

image_resource:
  type: docker-image
  source: {repository: node, tag: "6" }
inputs:
- name: cnets-chat-git
  path: /frontend
run:
  path: sh
  args:
  - -exc
  - |
    export API_URL={{cnets-backend-url}}
    npm install
    npm run build