version: '2'

volumes:
  mongo_data:
    driver: rancher-nfs
  mongo_dump:
    driver: rancher-nfs
services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
      - mongo_dump:/dump
    labels:
      io.rancher.scheduler.affinity:host_label_ne: public=true
    command: mongod --smallfiles --oplogSize 128
  mongo-lb:
    image: rancher/lb-service-haproxy:v0.7.9
    ports:
    - 27017:8087/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: public=true
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'