---

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

- name: npm-cache
  type: docker-image
  source:
    repository: ymedlop/npm-cache-resource
    tag: latest

resources:
- name: cnets-chat-git
  type: git
  source: &repo-source
    uri: {{cnets-chat-github-uri}}
    branch: {{cnets-chat-github-branch}}

- name: dependency-cache
  type: npm-cache
  source:
    <<: *repo-source
    paths:
      - frontend/package.json
    paths: # ... except that it's only interested in files listing dependencies
        - frontend/package.json
    project-path: frontend

- name: madhosoi-slack
  type: slack-notification
  source:
    url: {{slack-url}}

- name: backend-stage
  type: cf
  source:
    api: {{backend-cf-api}}
    username: {{backend-cf-username}}
    password: {{backend-cf-password}}
    organization: {{backend-cf-org}}
    space: {{backend-cf-space}}
    skip_cert_check: true

- name: frontend-stage
  type: cf
  source:
    api: {{frontend-cf-api}}
    username: {{frontend-cf-username}}
    password: {{frontend-cf-password}}
    organization: {{frontend-cf-org}}
    space: {{frontend-cf-space}}
    skip_cert_check: true

jobs:
- name: Install dependencies
  plan:
  - get: cnets-chat-git
    trigger: true
  - get: dependency-cache
  - put: madhosoi-slack
    params:
      channel: '#general'
      icon_url: http://185.170.26.160/apps/theming/logo?v=10
      text: Fujitsu CNETS Chat uploading!
      username: madhosoibot

- name: Build frontend
  plan:
  - get: cnets-chat-git
    passed: [Install dependencies]

  - get: dependency-cache
    passed: [Install dependencies]

  - task: build-frontend
    file: cnets-chat-git/ci/tasks/build-frontend.yml

- name: Deploy
  public: true
  serial: true
  plan:
  - get: cnets-chat-git
    passed: [Build frontend]
  - put: backend-stage
    params:
      manifest: cnets-chat-git/ci/assets/backend-manifest.yml
      path: cnets-chat-git/backend

  - put: frontend-stage
    params:
      manifest: cnets-chat-git/ci/assets/frontend-manifest.yml
      path: cnets-chat-git/frontend/public

  - put: madhosoi-slack
    params:
      channel: '#general'
      icon_url: http://185.170.26.160/apps/theming/logo?v=10
      text: Fujitsu CNETS Chat uploaded!
      username: madhosoibot